### ISSUE TITLE
Is this repo uptodate?

### ISSUE THREAD

**Issue by mohammad0omar** [Azure/AzureTestDrive#8]
I am working on building an ARM file for a project we are working on (test drive purposes), 

I came across this repo to test my template.json, i tried the below command:

`node test-drive.js validate ./samples/winvm/template.json `

and i got the below error

`           throw new Error(`No metadata nor default value found, parameter name: ${parameterName}"`);
            ^

Error: No metadata nor default value found, parameter name: vmName"
    at createParameter (/home/sisadmin/sis/arm/AzureTestDrive/lib/template-svc.js:41:19)
    at /home/sisadmin/sis/arm/AzureTestDrive/lib/template-svc.js:16:9
    at /home/sisadmin/sis/arm/AzureTestDrive/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/sisadmin/sis/arm/AzureTestDrive/node_modules/lodash/lodash.js:3032:24)
    at /home/sisadmin/sis/arm/AzureTestDrive/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/home/sisadmin/sis/arm/AzureTestDrive/node_modules/lodash/lodash.js:9410:14)
    at Object.createParameters (/home/sisadmin/sis/arm/AzureTestDrive/lib/template-svc.js:15:7)
    at validateTemplate (/home/sisadmin/sis/arm/AzureTestDrive/test-drive.js:95:34)
    at Object.<anonymous> (/home/sisadmin/sis/arm/AzureTestDrive/test-drive.js:21:5)
`

Taking this more, this seems on purpose in the testing code, its either to add a default value to our parameters or a type in the metadata section.

I would add a type but the ones in the list doesn't seems to fit my params.

Any idea how to test my arm file for test drive?

**Comment by mohammad0omar** [comment]
If you are reading this, I ended up creating a template script on Azure, and azure did the validation to me.
